# Generated by Django 4.1.7 on 2023-02-21 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='depart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.department', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='entry_time',
            field=models.DateField(verbose_name='Entry Time'),
        ),
    ]
