# Generated by Django 4.1.7 on 2023-02-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_accountadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='UserName')),
                ('password', models.CharField(max_length=32, verbose_name='PassWord')),
            ],
        ),
    ]
