# Generated by Django 4.1.7 on 2023-02-25 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.SmallIntegerField(choices=[(1, 'Urgent'), (2, 'Important'), (3, 'Temporary')], default=3, verbose_name='level')),
                ('title', models.CharField(max_length=64, verbose_name='title')),
                ('detail', models.TextField(verbose_name='detail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.admin', verbose_name='user')),
            ],
        ),
    ]
