# Generated by Django 4.1.7 on 2023-03-01 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='age',
            new_name='population',
        ),
    ]
